// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcYyLXv0H2NJoCb9Ewe297QaNe2jA4imY',
    appId: '1:1056618936490:web:299d37b2e40a54d925f8d3',
    messagingSenderId: '1056618936490',
    projectId: 'silabel-hariz',
    authDomain: 'silabel-hariz.firebaseapp.com',
    storageBucket: 'silabel-hariz.appspot.com',
    measurementId: 'G-2EHBPQ2WDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAsLq-vfRo-8GVpGYh2vbPFqlo8AU4p4',
    appId: '1:1056618936490:android:9aea31c508284cf125f8d3',
    messagingSenderId: '1056618936490',
    projectId: 'silabel-hariz',
    storageBucket: 'silabel-hariz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvtQiw3I8m2wN5Pi20J5hy6YdAZnpVBms',
    appId: '1:1056618936490:ios:42d9845a11c0013225f8d3',
    messagingSenderId: '1056618936490',
    projectId: 'silabel-hariz',
    storageBucket: 'silabel-hariz.appspot.com',
    androidClientId: '1056618936490-62493dq6einje94fl5t33d9stgoalefe.apps.googleusercontent.com',
    iosClientId: '1056618936490-7i4eoasre7l1g60pm3cppjoemj24178o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookReading',
  );
}
